{
 "title": "Kubernetes Connection Monitoring",
 "tags": [ "istio" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": "query_result(gcp:project)" },
   {
    "name": "top",
    "label": "top",
    "query": "query_result(count(topk(10, sort_desc(sum(increase(istio_requests_total:rate1m{destination_workload_namespace!=\"unknown\"}[$__range])) by (destination_workload_namespace)))) by (destination_workload_namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "UDP Test Rate",
   "type": "singlestat",
   "description": "This panel shows the rate in which UDP tests are being performed",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kconmon_udp_results_total[1m]))"
    }
   ]
  },
  {
   "title": "UDP Success Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(1 - (\n  (sum(increase(kconmon_udp_results_total{result=\"fail\"}[5m])) or\n  (sum(increase(kconmon_udp_results_total[5m])) * 0))\n  /\n  sum(increase(kconmon_udp_results_total[5m]))\n)) * 100\n",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "TCP Test Rate",
   "type": "singlestat",
   "description": "This panel shows the rate in which TCP tests are being performed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kconmon_tcp_results_total[1m]))"
    }
   ]
  },
  {
   "title": "TCP Success Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(1 - (\n  (sum(increase(kconmon_tcp_results_total{result=\"fail\"}[5m])) or\n  (sum(increase(kconmon_tcp_results_total[5m])) * 0))\n  /\n  sum(increase(kconmon_tcp_results_total[5m]))\n)) * 100\n",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "DNS Test Rate",
   "type": "singlestat",
   "description": "This panel shows the rate in which DNS tests are being performed",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kconmon_dns_results_total[1m]))"
    }
   ]
  },
  {
   "title": "DNS Success Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "(1 - (\n  (sum(increase(kconmon_dns_results_total{result=\"fail\"}[5m])) or\n  (sum(increase(kconmon_dns_results_total[5m])) * 0))\n  /\n  sum(increase(kconmon_dns_results_total[5m]))\n)) * 100\n",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  { "title": "Network Insight: UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Average Inter Zone RTT",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  This graph plots the average round-trip duration.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_duration_milliseconds) by (source_zone, destination_zone)",
     "legendFormat": "{{ source_zone }}: {{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Average Inter Zone RTT Variance",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  This graph plots the variance between the faster and the slowest response.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_duration_variance_milliseconds) by (source_zone, destination_zone)",
     "legendFormat": "{{ source_zone }}: {{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Average Loss by Source Zone",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  We wait a maximum of 250ms for a response packet, before considering it lost.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_loss) by (source_zone)",
     "legendFormat": "{{ source_zone }}"
    }
   ]
  },
  {
   "title": "Average Loss by Destination Zone",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  We wait a maximum of 250ms for a response packet, before considering it lost.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_loss) by (destination_zone)",
     "legendFormat": "{{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Average Loss by Source Node",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  We wait a maximum of 250ms for a response packet, before considering it lost.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_loss) by (source)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Average Loss by Destination Node",
   "type": "graph",
   "description": "Each UDP test sends 10 UDP packets every 5 seconds to a remote host, and that remote host replies with another packet.  We wait a maximum of 250ms for a response packet, before considering it lost.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_udp_loss) by (destination)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  { "title": "Network Insight: DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Successful Tests by Destination Host",
   "type": "graph",
   "description": "Shows DNS Tests by their destination",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kconmon_dns_results_total{result=\"pass\"}[1m])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Failing Tests by Destination Host",
   "type": "graph",
   "description": "Shows DNS Tests by their destination",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kconmon_dns_results_total{result=\"fail\"}[1m])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Failures by Source Zone",
   "type": "graph",
   "description": "This shows DNS test failures by source zone",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kconmon_dns_results_total{result=\"fail\"}[1m])) by (result, source_zone)",
     "legendFormat": "{{ source_zone }}"
    }
   ]
  },
  {
   "title": "Failures by Source Node",
   "type": "graph",
   "description": "This shows DNS test failures by source node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kconmon_dns_results_total{result=\"fail\"}[1m])) by (result, source)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  { "title": "Network Insight: TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Average Inter Zone Connect Duration",
   "type": "graph",
   "description": "This panel shows the average time it takes to perform a full TCP handshake and establish a connection",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_tcp_connect_milliseconds) by (source_zone, destination_zone)",
     "legendFormat": "{{ source_zone }}: {{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Average Inter Zone RTT",
   "type": "graph",
   "description": "This panel shows the average total TCP request duration, measured from the point the socket has been allocated on the local host, to the socket being closed following a response from the destination. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kconmon_tcp_duration_milliseconds) by (source_zone, destination_zone)",
     "legendFormat": "{{ source_zone }}: {{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Failures by Source Zone",
   "type": "graph",
   "description": "This test shows failures grouped by their source zone",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kconmon_tcp_results_total{result=\"fail\"}[1m])) by (source_zone)",
     "legendFormat": "{{ source_zone }}"
    }
   ]
  },
  {
   "title": "Failures by Destination Zone",
   "type": "graph",
   "description": "This test shows failures grouped by their source zone",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kconmon_tcp_results_total{result=\"fail\"}[1m])) by (destination_zone)",
     "legendFormat": "{{ destination_zone }}"
    }
   ]
  },
  {
   "title": "Failures by Source Node",
   "type": "graph",
   "description": "This test shows failures grouped by their source node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kconmon_tcp_results_total{result=\"fail\"}[1m])) by (source)",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Failures by Destination Node",
   "type": "graph",
   "description": "This test shows failures grouped by their destination node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kconmon_tcp_results_total{result=\"fail\"}[1m])) by (destination)",
     "legendFormat": "{{ destination }}"
    }
   ]
  }
 ]
}