{
 "title": "ElasticSearch 7 Backup",
 "description": "ElasticSearch cluster stats.\r\n\r\nRevision 1 of this dashboard is the same as the Infinity Dashboard Revision 4 (https://grafana.com/dashboards/2322)\r\n\r\nThis is a cleaned up copy with all control characters removed from the dashboard file.  When downloading version 4 of the original Infinity elasticsearch dashboard via curl, the resulting file is corrupted with a missing final curly brace.\r\n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(es_indices_doc_number{namespace=\"$namespace\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(es_index_doc_number{}, namespace)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "es_cluster_status{namespace=\"$namespace\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (es_process_cpu_percent{cluster=\"$cluster\",namespace=\"$namespace\"} ) / count (es_process_cpu_percent{cluster=\"$cluster\",namespace=\"$namespace\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (es_jvm_mem_heap_used_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}) / sum (es_jvm_mem_heap_max_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(es_circuitbreaker_tripped_count{cluster=\"$cluster\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "es_process_file_descriptors_open_number{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_pending_tasks_number{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_nodes_number{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_datanodes_number{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_number{type=\"active_primary\", cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_number{type=\"active\", cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_number{type=\"initializing\", cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "singlestat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_number{type=\"relocating\", cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_number{type=\"unassigned\", cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Percent of active shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "es_cluster_shards_active_percent{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(es_jvm_gc_collection_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_jvm_gc_collection_time_seconds{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total translog operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_translog_operations_number{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_translog_size_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  { "title": "Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Tripped for breakers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "es_circuitbreaker_tripped_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{name}} - {{node}}"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "es_circuitbreaker_estimated_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{name}} - {{node}}"
    },
    {
     "expr": "es_circuitbreaker_limit_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "LIMIT {{name}} - {{node}}"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "es_os_load_average_one_minute{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "One Minute - {{node}}"
    },
    {
     "expr": "es_os_load_average_five_minutes{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "Five Minute - {{node}}"
    },
    {
     "expr": "es_os_load_average_fifteen_minutes{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "legendFormat": "Fifteen Minute - {{node}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "es_process_cpu_percent{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "es_jvm_mem_heap_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}} used"
    },
    {
     "expr": "es_jvm_mem_heap_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}} max"
    },
    {
     "expr": "es_jvm_mem_pool_peak_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "es_jvm_mem_heap_committed_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}} committed"
    },
    {
     "expr": "es_jvm_mem_heap_max_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}} max"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk Usage %" }
   ],
   "targets": [
    {
     "expr": "1 - (es_fs_total_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\"} / es_fs_total_total_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(es_transport_tx_bytes_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: sent "
    },
    {
     "expr": "-irate(es_transport_rx_bytes_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: received"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Documents count on node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "es_indices_doc_number{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_indexing_index_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "irate(es_indices_doc_deleted_number{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_merges_total_docs_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "irate(es_indices_merges_total_size_bytes{cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_search_query_time_seconds{context=\"primaries\", cluster=\"$cluster\", namespace=\"$namespace\"}[$interval]) ",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_merges_total_time_seconds{context=\"primaries\", cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_indexing_index_time_seconds{context=\"primaries\", cluster=\"$cluster\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_index_indexing_throttle_time_seconds{context=\"primaries\", cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Total Operations  rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_indexing_index_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "rate(es_indices_search_query_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "rate(es_indices_search_fetch_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "rate(es_indices_merges_total_number{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "rate(es_indices_refresh_total_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "rate(es_indices_flush_total_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "rate(es_indices_get_exists_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "rate(es_indices_get_missing_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "rate(es_indices_get_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get"
    },
    {
     "expr": "rate(es_indices_indexing_delete_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(es_indices_indexing_index_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "irate(es_indices_search_query_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "irate(es_indices_search_fetch_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "irate(es_indices_merges_total_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "irate(es_indices_refresh_total_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "irate(es_indices_flush_total_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "irate(es_indices_get_exists_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "irate(es_indices_get_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get_time"
    },
    {
     "expr": "irate(es_indices_get_missing_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "irate(es_indices_indexing_delete_time_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{node}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 }
  },
  {
   "title": "Count of documents on primary shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "es_index_doc_number{context=\"primaries\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data on only primary shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "es_index_store_size_bytes{context=\"primaries\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with all shards on all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "es_index_store_size_bytes{context=\"total\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  }
 ]
}