{
 "title": "Jenkins Span Build Dashboard",
 "description": "View of Jenkins Spans and Operations.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "build_name",
    "label": "Build Name",
    "query": {
     "query": "label_values(calls_total{service_name=~\"jenkins\"}, build_name)"
    }
   },
   {
    "name": "build_number",
    "label": "Build Number",
    "query": {
     "query": "label_values(calls_total{service_name=~\"jenkins\", build_name=~\"$build_name\"}, build_number)"
    }
   },
   { "name": "filter", "label": "Regex Filter", "query": ".+" },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(calls_total{service_name=~\"jenkins\",span_name=~\".*$filter.*\", build_name=~\"$build_name\", build_number=~\"$build_number\"}, span_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Build Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Build Duration",
   "type": "table",
   "description": "Average build duration, filterable by build name and number.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "duration_milliseconds_sum{span_name=~\"Agent\",build_name=~\"$build_name\",build_number=~\"$build_number\"}",
     "legendFormat": "{{build_name}}: {{build_number}}"
    }
   ]
  },
  {
   "title": "Top 10 Longest Operations",
   "type": "table",
   "description": "The 10 longest averaging build operations.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, avg by (build_name, span_name) (duration_milliseconds_sum{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"jenkins\", span_name!=\"Agent\", span_name!~\".*Parallel branch:.*\", span_name!~\".*bin/cobra.*\",span_name=~\"$operation\"} / duration_milliseconds_count{build_name=~\"$build_name\", build_number=~\"$build_number\",service_name=~\"jenkins\", span_name!=\"Agent\", span_name!~\".*Parallel branch:.*\", span_name!~\".*bin/cobra.*\",span_name=~\"$operation\"}))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Operation Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Operation Durations",
   "type": "timeseries",
   "description": "Shows the top 50 latencies by operation/span name. ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(50, avg by (build_name, span_name) (duration_milliseconds_sum{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"jenkins\", span_name!=\"Agent\", span_name!~\".*Parallel branch:.*\", span_name!~\".*bin/cobra.*\",span_name=~\"$operation\"} / duration_milliseconds_count{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"jenkins\", span_name!=\"Agent\", span_name!~\".*Parallel branch:.*\", span_name!~\".*bin/cobra.*\",span_name=~\"$operation\"}))",
     "legendFormat": "{{build_name}} {{build_number}}: {{span_name}}"
    }
   ]
  },
  {
   "title": "Git Operation Durations",
   "type": "timeseries",
   "description": "Top 50 Git operations, sorted by highest.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(50, avg by (build_name, span_name) (duration_milliseconds_sum{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"jenkins\", span_name=~\".*git.*\"} / duration_milliseconds_count{build_name=~\"$build_name\", build_number=~\"$build_number\",service_name=~\"jenkins\", span_name=~\".*git.*\"}))",
     "legendFormat": "{{build_name}} {{build_number}}: {{span_name}}"
    }
   ]
  },
  {
   "title": "Stage Durations",
   "type": "timeseries",
   "description": "Top 50 Stage operations, sorted by highest.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(50, avg by (build_name, span_name) (duration_milliseconds_sum{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"jenkins\", span_name=~\".*Stage.*\"} / duration_milliseconds_count{build_name=~\"$build_name\", build_number=~\"$build_number\",service_name=~\"jenkins\", span_name=~\".*Stage.*\"}))",
     "legendFormat": "{{build_name}} {{build_number}}: {{span_name}}"
    }
   ]
  },
  {
   "title": "Span Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 25 Span Count By Operation",
   "type": "table",
   "description": "Shows the top 25 non-failing spans.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum(calls_total{service_name=~\"jenkins\", span_name=~\"$operation\",build_name=~\"$build_name\",build_number=~\"$build_number\"}) by (span_name,build_name)) "
    }
   ]
  },
  {
   "title": "Top 25 Error Count by Operation",
   "type": "table",
   "description": "Shows the top 25 errors spans.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"jenkins\", span_name=~\"$operation\",build_name=~\"$build_name\",build_number=~\"$build_number\"}) by (span_name,build_name))"
    }
   ]
  }
 ]
}