{
 "title": "Jenkins Build Metrics",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "repository",
    "query": {
     "query": "label_values(jenkins_builds_health_score, repo)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(jenkins_builds_health_score{repo=\"$repository\"}, jenkins_job)"
    }
   },
   {
    "name": "build",
    "query": {
     "query": "label_values(jenkins_builds_build_result{repo=\"$repository\", jenkins_job=~\"$job\"}, number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rolling Count",
   "type": "table",
   "description": "Returns count for jobs that still exist in Jenkins.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_builds_failed_build_count_total{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\"}+0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jenkins_builds_success_build_count_total{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\"}+0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Build Statistics (Time Range)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 >= $__from",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 <= $__to",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_duration_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_result_ordinal{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    }
   ]
  },
  {
   "title": "Build Statistics (Time Range)",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 >= $__from",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 <= $__to",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_duration_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_result_ordinal{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    }
   ]
  },
  {
   "title": "Build Duration and Timestamps  (Time Range)",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 >= $__from",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0 <= $__to",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_duration_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "jenkins_builds_build_result_ordinal{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "{{number}} {{buildable}}"
    }
   ]
  },
  {
   "title": "Build Stages - Last Build",
   "type": "barchart",
   "description": "Stage times for the LAST build of a Jenkins Job. We do not have per run metrics for this key.",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_builds_last_stage_duration_milliseconds_summary_sum{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\"}+0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Count (Time Range)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "(label_join(jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0, \"combined_label\", \":\", \"jenkins_job\", \"number\") >= $__from) and (label_join(jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0, \"combined_label\", \":\", \"jenkins_job\", \"number\") <= $__to) OR on() vector(0)",
     "legendFormat": "{{number}} {{buildable}}"
    },
    {
     "expr": "label_join(jenkins_builds_build_result_ordinal{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0, \"combined_label\", \":\", \"jenkins_job\", \"number\")",
     "legendFormat": "{{number}} {{buildable}}"
    }
   ]
  },
  {
   "title": "Build Times Plot  (Time Range)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jenkins_builds_build_start_time_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jenkins_builds_build_duration_milliseconds{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jenkins_builds_build_result_ordinal{namespace=\"$namespace\", repo=\"$repository\", jenkins_job=~\"$job\", number=~\"$build\"}+0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}