{
 "title": "Jenkins Controller Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_responseCodes_serverError_total{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "description": "Average memory usage of specified Jenkins instance(s) in the namespace",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_memory_total_used{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace) / sum(vm_memory_total_max{namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "JVM Memory Heap Ratio",
   "type": "graph",
   "description": "Aggregate ratio of memory used/total, in the Jenkins JVM heap that is used for object allocation",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (vm_memory_heap_usage{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "JVM CPU Load",
   "type": "timeseries",
   "description": "The rate of CPU time usage by the JVM per unit time on the Jenkins controller. Equivalent to the number of CPU cores being used by the Jenkins JVM.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (vm_cpu_load{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Jenkins Disk Usage for instance(s) in the namespace",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, directory) (jenkins_disk_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "namespace={{namespace}}, directory={{directory}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "The rate at which the Jenkins Web UI is receiving requests, calculated over the current time interval",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(http_requests_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Average HTTP Requests: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (increase(http_responseCodes_badRequest_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "HTTP/500: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (increase(http_responseCodes_ok_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "HTTP/200: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (increase(http_responseCodes_forbidden_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "HTTP/403: {{namespace}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "table-old",
   "description": "Counts total build nodes, online + offline",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "jenkins_node_count_value{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Jenkins Health",
   "type": "table",
   "description": "Reported health check score from Dropwizard Metrics API",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace) (jenkins_health_check_score{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "table-old",
   "description": "Counts offline build nodes that are connected to this master",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "jenkins_node_offline_value{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Plugin Updates Available",
   "type": "table-old",
   "description": "Amount of plugins that are available for updating",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "sum by (namespace) (jenkins_plugins_withUpdate{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (http_responseCodes_serverError_total{namespace=~\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "table-old",
   "description": "The number of threads that have a currently detected deadlock with at least one other thread.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "vm_deadlock_count{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Job Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Job Success Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_runs_success_total{namespace=~\"$namespace\",pod=~\"$pod\"}) / sum(jenkins_runs_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}) * 100"
    }
   ]
  },
  {
   "title": "Avg Build Duration Minutes",
   "type": "graph",
   "description": "Aggregate ",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (jenkins_job_building_duration{quantile=\"0.5\",namespace=~\"$namespace\",pod=~\"$pod\"}) / 60",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Runs Per Day",
   "type": "graph",
   "description": "Aggregate runs ",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jenkins_runs_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(jenkins_runs_failure_total{namespace=~\"$namespace\",pod=~\"$pod\"}[24h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(jenkins_runs_aborted_total{namespace=~\"$namespace\",pod=~\"$pod\"}[24h]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(increase(jenkins_runs_success_total{namespace=~\"$namespace\",pod=~\"$pod\"}[24h]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "table",
   "description": "The number of jobs in Jenkins",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jenkins_job_count_value{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Queue Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Queue Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (jenkins_queue_size_value{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Total Queue Size: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (jenkins_queue_buildable_value{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Buildable Jobs in Queue: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (jenkins_queue_stuck_value{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Stuck Jobs in Queue: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (jenkins_queue_blocked_value{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Blocked Jobs in Queue: {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (jenkins_queue_pending_value{namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Pending Jobs in Queue: {{namespace}}"
    }
   ]
  },
  { "title": "Build Failure Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Build Failure Analyzer Causes",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cause) (increase(jenkins_bfa{namespace=~\"$namespace\", pod=~\"$pod\", category=\"\"}[$__range])) != 0",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Build Failure Analyzer Category",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (increase(jenkins_bfa{namespace=~\"$namespace\", pod=~\"$pod\", cause=\"\"}[$__range])) != 0",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}