{
 "title": "Kube Quotas (Namespace)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "typeVirtual",
    "label": "Type Virtual",
    "query": "label_values(kube_resourcequota, resource)"
   },
   { "name": "typePhysical", "label": "Type Physical", "query": "memory, cpu,ephemeral-storage" },
   { "name": "nature", "label": "Nature", "query": "requests,limits" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(kube_pod_status_phase{phase=\"Running\",namespace=~\"$namespace\"}==1)"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Resources Gauges (last minute)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Quota: requests.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "typePhysical",
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"requests.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: requests.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"requests.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: requests.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"requests.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: limits.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "repeat": "typePhysical",
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"limits.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: limits.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"limits.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: limits.$typePhysical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"limits.$typePhysical\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.$typePhysical\"}\n)\n*100"
    }
   ]
  },
  { "title": "Physical Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory ",
   "type": "graph",
   "description": "Limits: straight lines\n\nRequests: dashed lines\n\nUsed: filled area",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.memory\"}\n)",
     "legendFormat": "namespace request quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.memory\"}\n)",
     "legendFormat": "namespace limit quota"
    },
    {
     "expr": "sum( \n    kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"memory\"}\n)",
     "legendFormat": "pod request sum"
    },
    {
     "expr": "sum( \n    kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"memory\"}\n)",
     "legendFormat": "pod limit sum"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", container_name!=\"POD\", pod_name=~\"$pod\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Limits: straight lines\n\nRequests: dashed lines\n\nUsed: filled area",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "cores/Δt" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.cpu\"}\n)",
     "legendFormat": "namespace request quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.cpu\"}\n)",
     "legendFormat": "namespace limit quota"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"cpu\"}\n)",
     "legendFormat": "pod request sum"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"cpu\"}\n)",
     "legendFormat": "pod limit sum"
    },
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m]\n  )\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "graph",
   "description": "Limits: straight lines\n\nRequests: dashed lines\n\nUsed: filled area",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "ephemeral storage/Δt" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"requests.ephemeral-storage\"}\n)",
     "legendFormat": "namespace request quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"limits.ephemeral-storage\"}\n)",
     "legendFormat": "namespace limit quota"
    },
    {
     "expr": "sum(\n   kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\",resource=\"ephemeral_storage\"}\n)",
     "legendFormat": "pod request sum"
    },
    {
     "expr": "sum(\n   kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\",resource=\"ephemeral_storage\"}\n)",
     "legendFormat": "pod limit sum"
    },
    {
     "expr": "sum(\n  container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\",pod=~\"$pod\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Virtual Resources Gauges (last minute)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "repeat": "typeVirtual",
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)\n/\nsum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)\n*100"
    }
   ]
  },
  { "title": "Virtual Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "repeat": "typeVirtual",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  },
  {
   "title": "Quota: $typeVirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"hard\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "namespace quota"
    },
    {
     "expr": "sum(\n    kube_resourcequota{namespace=~\"$namespace\",type=\"used\",resource=\"$typeVirtual\"}\n)",
     "legendFormat": "actually used"
    }
   ]
  }
 ]
}