{
 "title": "Ephemeral Storage",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows pod ephemeral storage usage.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": "label_values(node)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_fs_usage_bytes{node=~\"$Node\"}, namespace)"
   },
   { "name": "filter", "label": "Filter" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_fs_usage_bytes{node=~\"$Node\",namespace=~\"$namespace\", pod_name=~\".*$filter.*\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Ephemeral Storage usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\", node=~\"$Node\"}) / sum (kube_node_status_allocatable{resource=\"ephemeral_storage\", node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"ephemeral_storage\", node=~\"$Node\"})"
    }
   ]
  },
  { "title": "Pods Ephemeral Storage usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pods Ephemeral Storage usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$namespace\",pod_name=~\"$pod\",pod_name=~\".*$filter.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods Ephemeral Storage % usage ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$namespace\",pod=~\"$pod\",pod=~\".*$filter.*\"}) by (pod)\n/\nsum(kube_pod_container_resource_limits{node=~\"^$Node$\",namespace=~\"$namespace\",pod=~\"$pod\",pod=~\".*$filter.*\",resource=\"ephemeral_storage\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}