{
 "title": "Namespace Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (pod) (kube_pod_status_ready{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (namespace) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1d]))"
    }
   ]
  },
  {
   "title": "CPU  Requested",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_spec_memory_limit_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Storage Requested",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (namespace) (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container_name=~\".*\", container_name!=\"POD\"}[5m])) / sum by (namespace) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"})",
     "legendFormat": "{{ namespace }} Usage"
    },
    {
     "expr": "sum by (namespace) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) / sum by (namespace) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"})",
     "legendFormat": "{{ namespace }} Request"
    },
    { "expr": "1", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"$namespace\", container_name!=\"POD\"})",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum by (namespace) (container_spec_memory_limit_bytes{namespace=\"$namespace\", container_name!=\"POD\"})",
     "legendFormat": "{{ namespace }} Limit"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}} Sent"
    },
    {
     "expr": "sum by(namespace) (irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) * -1",
     "legendFormat": "{{namespace}} Received"
    }
   ]
  },
  {
   "title": "Disk I/O per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (irate(container_fs_reads_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}} read"
    },
    {
     "expr": "sum by (namespace) (irate(container_fs_writes_bytes_total{namespace=\"$namespace\"}[5m])) * -1",
     "legendFormat": "{{namespace}} written"
    }
   ]
  }
 ]
}