{
 "title": "NGINX",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(nginx_up, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nginx_up{namespace=~\"$namespace\", pod=~\".*$filter.*\"}, pod)"
   },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "conn/s" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} active"
    },
    {
     "expr": "nginx_connections_reading{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} reading"
    },
    {
     "expr": "nginx_connections_waiting{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} waiting"
    },
    {
     "expr": "nginx_connections_writing{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} writing"
    }
   ]
  },
  {
   "title": "Throughput (req/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{namespace=~\"$namespace\",pod=~\".*$filter.*\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}