{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "otelcol_process_runtime_heap_alloc_bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Accepted vs Refused ",
   "type": "graph",
   "description": "Rate of spans successfully accepted vs refused",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused"
    }
   ]
  },
  {
   "title": "Logs Accepted vs Refused",
   "type": "graph",
   "description": "Rate of logs successfully accepted vs refused",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records[1m])) by (receiver)",
     "legendFormat": "{{receiver}} logs accepted"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_log_records[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} logs refused"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spans Exported",
   "type": "timeseries",
   "description": "Rate of spans successfully exported",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans[1m])) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Logs Exported vs Failed",
   "type": "graph",
   "description": "Rate of logs successfully exported",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed"
    }
   ]
  },
  {
   "title": "Metrics Exported",
   "type": "timeseries",
   "description": "Total of metrics successfully exported per minute",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_metric_points[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}