{
 "title": "Passenger",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(passenger_wait_list_size, namespace)"
   },
   { "name": "filter", "label": "Filter", "query": ".+" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(passenger_wait_list_size{namespace=~\"$namespace\", pod=~\".*$filter.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request queue depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "passenger_wait_list_size{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests per minute" }
   ],
   "targets": [
    {
     "expr": "increase(passenger_cumulative_requests_processed{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cumulative Requests Processed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(passenger_cumulative_requests_processed[$__range])",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}