{
 "title": "Pod Resource Usage",
 "tags": [ "prod" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "filter", "label": "Regex Filter", "query": ".+" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{image!=\"\", namespace=~\"$namespace\", pod=~\".*$filter.*\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minimum Memory Requested",
   "type": "singlestat",
   "description": "Minimum memory that nodes are expected to have free for the given pods to be allocated there on aggregate.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "description": "Maximum memory that the given pods are allowed to consume on aggregate.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Minimum CPU Cores Requested",
   "type": "singlestat",
   "description": "Aggregate of minimum CPU core time that the nodes must have free for the given pods to be scheduled on those machines.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Maximum CPU Limits",
   "type": "singlestat",
   "description": "Aggregate of maximum CPU time that the given pods are allowed to consume.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Current Memory Allocation Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}\n)\n/\nsum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  rate(\n      container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}[1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Current CPU Allocation Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  rate(\n      container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}[1m]\n  )\n)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}\n)"
    }
   ]
  },
  { "title": "Stats per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Allocated Memory Usage",
   "type": "graph",
   "description": "Memory working set bytes over memory usage limit. Brief spikes over 100% are expected due to sampling noise and kernel allocation heuristics.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}\n  ) by (pod_name),\n  \"pod\", \n  \"$1\",\n  \"pod_name\",\n  \"(.*)\"\n)\n/ on (pod)\nsum(\n  kube_pod_container_resource_limits_memory_bytes{}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Allocated CPU Usage",
   "type": "graph",
   "description": "CPU time use over CPU limit. Brief spikes over 100% are expected due to sampling noise and kernel scheduling heuristics.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}[1m]\n    )\n  ) by (pod_name),\n  \"pod\", \n  \"$1\",\n  \"pod_name\",\n  \"(.*)\"\n)\n/ on (pod)\nsum(\n  kube_pod_container_resource_limits_cpu_cores{}\n) by (pod)",
     "legendFormat": "{{  pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Aggregate memory consumed (measured by Working Set Size) by the given pods.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "working set size" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}\n  ) by (pod_name),\n  \"pod\", \n  \"$1\",\n  \"pod_name\",\n  \"(.*)\"\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregate of CPU cores utilized by the given pods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}[1m]\n  )\n) by (pod_name)",
     "legendFormat": "{{  pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Allocation Denials",
   "type": "graph",
   "description": "Count of memory allocation denials (aka failed malloc()s) over time for the given pods due to memory size limits.\n\nA non-zero number of denials does not necessarily mean that the application is being OOM-killed, but it is severely correlated to it when that application  memory quota is undersized.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "denials/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    rate(\n      container_memory_failcnt{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]\n    )\n  ) by (pod_name),\n  \"pod\", \n  \"$1\",\n  \"pod_name\",\n  \"(.*)\"\n)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Denied CPU usage",
   "type": "graph",
   "description": "Sum of CPU cores that the given pods asked to be scheduled on for execution but were denied by usage limits.\n\nThis graph is useful to detect situations where CPU is being limited during small bursts of activity, which could be causing slow application responses, but the sampling rate is unable to spot those short periods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    rate(\n      container_cpu_cfs_throttled_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]\n    )\n  ) by (pod_name),\n  \"pod\", \n  \"$1\",\n  \"pod_name\",\n  \"(.*)\"\n)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Stats per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Notice",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "content": "All metrics below sum the data only from the pods filtered above."
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Sum of all the memory used (Working Set Size) by the given pods for each node on the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "working set size" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregate of CPU cores utilized by the given pods on each node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\"}[1m]\n    )\n) by (instance)",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "Memory Allocation Denials",
   "type": "graph",
   "description": "Count of memory allocation denials (aka failed malloc()s) over time for the given pods due to memory size limits on each node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "denials/s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_memory_failcnt{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]\n  )\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Denied CPU usage",
   "type": "graph",
   "description": "Sum of CPU cores that the given pods asked to be scheduled for execution on but were denied by usage limits on each node.\n\nThis graph is useful to detect overcrowded nodes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_cfs_throttled_seconds_total{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*$filter.*\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]\n  )\n) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}