{
 "title": "Redis",
 "description": "Redis",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "filter", "label": "Regex Filter", "query": ".+" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(redis_instance_info{namespace=~\"$namespace\", pod=~\".*$filter.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(redis_memory_used_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"})  / sum(redis_memory_max_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}) )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  sum(\n    rate(redis_commands_processed_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[1m])\n  ) by (pod),\n  \"pod\", \n  \"$1\",\n  \"pod\",\n  \"(.*)\"\n)"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}) - sum (redis_db_keys_expiring{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=~\"$namespace\", pod=~\".*$filter.*\", pod=~\"$pod\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}