{
 "title": "Sidekiq",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Enqueuing rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(sidekiq_enqueued_jobs{namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(sidekiq_processed_jobs_total{namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Failed growth",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(increase(sidekiq_failed_jobs_total{namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Retry jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sidekiq_retry_jobs{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Dead jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sidekiq_dead_jobs{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Enqueued jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sidekiq_enqueued_jobs{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sidekiq_busy_workers{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sidekiq_scheduled_jobs{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Queues latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(sidekiq_queue_latency_seconds{namespace=~\"$namespace\", name!~\"sidekiq_alive.*\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(rate(sidekiq_processed_jobs_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "processing rate"
    },
    {
     "expr": "rate(sidekiq_queue_latency_seconds{namespace=~\"$namespace\", name=~\"sidekiq_alive.*\"}[1m])",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Queue enqueued jobs",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_queue_enqueued_jobs{namespace=~\"$namespace\", name!~\"sidekiq_alive.*\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sidekiq_queue_enqueued_jobs{namespace=~\"$namespace\", name=~\"sidekiq_alive.*\"}",
     "legendFormat": "pods"
    }
   ]
  }
 ]
}