{
 "title": "Spanmetrics Dashboard",
 "description": "Spanmetrics way of application view.",
 "tags": [
  "apm",
  "spanmetrics",
  "opentelemetry"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(calls_total, service_name)"
    }
   },
   { "name": "filter", "label": "Regex Filter" },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(calls_total{service_name=~\"$service\", span_name=~\".*$filter.*\", build_name=~\"$build_name\", build_number=~\"$build_number\"}, span_name)"
    }
   },
   {
    "name": "build_name",
    "label": "Build Name",
    "query": {
     "query": "label_values(calls_total{service_name=~\"$service\"}, build_name)"
    }
   },
   {
    "name": "build_number",
    "label": "Build Number",
    "query": {
     "query": "label_values(calls_total{service_name=~\"$service\", build_name=~\"$build_name\"}, build_number)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Build Level - Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 7 Spans by Build Name",
   "type": "bargauge",
   "description": "Shows the span count by build name.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(calls_total{service_name=~\"$service\", span_name=~\"$operation\",build_name=~\"$build_name\", build_number=~\"$build_number\"}) by (service_name, build_name))",
     "legendFormat": "{{build_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Error Spans By Build Names",
   "type": "bargauge",
   "description": "Shows the error span count by build name.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$operation\",build_name=~\"$build_name\", build_number=~\"$build_number\"}) by (service_name, build_name))",
     "legendFormat": "{{build_name}}"
    }
   ]
  },
  {
   "title": "Operations Level - Spans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 25 Span Count By Operation",
   "type": "table",
   "description": "Shows the top 25 non-failing spans.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum(calls_total{service_name=~\"$service\", span_name=~\"$operation\",build_name=~\"$build_name\",build_number=~\"$build_number\"}) by (span_name,service_name,build_name)) "
    }
   ]
  },
  {
   "title": "Top 25 Error Span Count by Operation",
   "type": "table",
   "description": "Shows the top 25 errors spans.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, sum(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$operation\",build_name=~\"$build_name\",build_number=~\"$build_number\"}) by (span_name,service_name,build_name))"
    }
   ]
  },
  {
   "title": "Operation Level - Latencies/Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 3x3 - Operation Latency - quantile95",
   "type": "gauge",
   "description": "Shows the top 7 operation latencies rate of change, in the form of histogram buckets.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{service_name=~\"$service\", span_name=~\"$operation\", build_name=~\"$build_name\", build_number=~\"$build_number\",}[$__range])) by (le,span_name,build_name,build_number))) > 0",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies Mean Over Range ",
   "type": "bargauge",
   "description": "Shows the top 7 operation latency means, by rate of increase.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (span_name,service_name,build_name,build_number)(increase(duration_milliseconds_sum{service_name=~\"${service}\", span_name=~\"$operation\", build_name=~\"$build_name\", build_number=~\"$build_number\",}[$__range]) / increase(duration_milliseconds_count{service_name=~\"${service}\",span_name=~\"$operation\", build_name=~\"$build_name\", build_number=~\"$build_number\",}[$__range]))) > 0",
     "legendFormat": "{{span_name}} [{{service_name}}]"
    }
   ]
  },
  {
   "title": "Top 50 Durations By Operation",
   "type": "timeseries",
   "description": "Shows the top 50 latencies by operation/span name. Displays by duration, not by rate.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(50, avg by (build_name, service_name, span_name) (duration_milliseconds_sum{build_name=~\"$build_name\", build_number=~\"$build_number\", service_name=~\"$service\", span_name=~\"$operation\"} / duration_milliseconds_count{build_name=~\"$build_name\", build_number=~\"$build_number\",service_name=~\"$service\", span_name=~\"$operation\"}))",
     "legendFormat": "{{build_name}} {{build_number}}: {{span_name}}"
    }
   ]
  }
 ]
}